START TRANSACTION;

-- カテゴリ名の文字列長を修正（20->30）
ALTER TABLE product_category ALTER COLUMN name TYPE character varying(30);
-- 渡邊君実装のアカウントロック関連
ALTER TABLE employee_account ADD AccessFailedCount INT DEFAULT 0 NOT NULL;
ALTER TABLE employee_account ADD LockoutEnd TIMESTAMPTZ NULL;


-- 新規テーブルの作成
CREATE TABLE customer (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    customer_uuid uuid NOT NULL,
    name character varying(20) NOT NULL,
    address1 character varying(100) NOT NULL,
    address2 character varying(100) NOT NULL,
    phone_number character varying(20) NOT NULL,
    mail_address character varying(200) NOT NULL,
    username character varying(30) NOT NULL,
    password character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_customer" PRIMARY KEY (id)
);

CREATE TABLE order_status (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    CONSTRAINT "PK_order_status" PRIMARY KEY (id)
);

CREATE TABLE payment_method (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    CONSTRAINT "PK_payment_method" PRIMARY KEY (id)
);

CREATE TABLE orders (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    order_uuid uuid NOT NULL,
    order_date timestamp with time zone NOT NULL,
    amount_total integer NOT NULL,
    customer_id integer NOT NULL,
    order_status_id integer NOT NULL,
    payment_method_id integer NOT NULL,
    CONSTRAINT "PK_orders" PRIMARY KEY (id),
    CONSTRAINT "FK_orders_customer_customer_id" FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_orders_order_status_order_status_id" FOREIGN KEY (order_status_id) REFERENCES order_status (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_orders_payment_method_payment_method_id" FOREIGN KEY (payment_method_id) REFERENCES payment_method (id) ON DELETE RESTRICT
);

CREATE TABLE orders_detail (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    count integer NOT NULL,
    CONSTRAINT "PK_orders_detail" PRIMARY KEY (id),
    CONSTRAINT "FK_orders_detail_orders_order_id" FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_orders_detail_product_product_id" FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_customer_customer_uuid" ON customer (customer_uuid);

CREATE UNIQUE INDEX "IX_customer_mail_address" ON customer (mail_address);

CREATE UNIQUE INDEX "IX_customer_username" ON customer (username);

CREATE UNIQUE INDEX "IX_order_status_name" ON order_status (name);

CREATE INDEX "IX_orders_customer_id" ON orders (customer_id);

CREATE INDEX "IX_orders_order_status_id" ON orders (order_status_id);

CREATE UNIQUE INDEX "IX_orders_order_uuid" ON orders (order_uuid);

CREATE INDEX "IX_orders_payment_method_id" ON orders (payment_method_id);

CREATE INDEX "IX_orders_detail_order_id" ON orders_detail (order_id);

CREATE INDEX "IX_orders_detail_product_id" ON orders_detail (product_id);

CREATE UNIQUE INDEX "IX_payment_method_name" ON payment_method (name);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260714044207_AddForCustomerAPI', '10.0.9');

COMMIT;

