CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE department (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    department_uuid uuid NOT NULL,
    name character varying(100) NOT NULL,
    CONSTRAINT "PK_department" PRIMARY KEY (id)
);

CREATE TABLE product_category (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    category_uuid uuid NOT NULL,
    name character varying(20) NOT NULL,
    CONSTRAINT "PK_product_category" PRIMARY KEY (id)
);

CREATE TABLE employee (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    employee_uuid uuid NOT NULL,
    department_id integer NOT NULL,
    name character varying(100) NOT NULL,
    name_kana character varying(100) NOT NULL,
    CONSTRAINT "PK_employee" PRIMARY KEY (id),
    CONSTRAINT "FK_employee_department_department_id" FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE RESTRICT
);

CREATE TABLE product (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    product_uuid uuid NOT NULL,
    product_category_id integer NOT NULL,
    name character varying(20) NOT NULL,
    price integer NOT NULL,
    image_url character varying(200),
    delete_flag integer NOT NULL,
    CONSTRAINT "PK_product" PRIMARY KEY (id),
    CONSTRAINT "FK_product_product_category_product_category_id" FOREIGN KEY (product_category_id) REFERENCES product_category (id) ON DELETE RESTRICT
);

CREATE TABLE employee_account (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    account_uuid uuid NOT NULL,
    employee_id integer NOT NULL,
    name character varying(20) NOT NULL,
    password character varying(200) NOT NULL,
    CONSTRAINT "PK_employee_account" PRIMARY KEY (id),
    CONSTRAINT "FK_employee_account_employee_employee_id" FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE RESTRICT
);

CREATE TABLE product_stock (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    stock_uuid uuid NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT "PK_product_stock" PRIMARY KEY (id),
    CONSTRAINT "FK_product_stock_product_product_id" FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT
);

CREATE INDEX "IX_employee_department_id" ON employee (department_id);

CREATE UNIQUE INDEX "IX_employee_employee_uuid" ON employee (employee_uuid);

CREATE UNIQUE INDEX "IX_employee_account_account_uuid" ON employee_account (account_uuid);

CREATE INDEX "IX_employee_account_employee_id" ON employee_account (employee_id);

CREATE UNIQUE INDEX "IX_employee_account_name" ON employee_account (name);

CREATE INDEX "IX_product_product_category_id" ON product (product_category_id);

CREATE UNIQUE INDEX "IX_product_product_uuid" ON product (product_uuid);

CREATE UNIQUE INDEX "IX_product_category_category_uuid" ON product_category (category_uuid);

CREATE UNIQUE INDEX "IX_product_stock_product_id" ON product_stock (product_id);

CREATE UNIQUE INDEX "IX_product_stock_stock_uuid" ON product_stock (stock_uuid);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260707073908_InitialCreate', '10.0.9');

COMMIT;

